# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f33ee6a4519b2f04b8bb1287a33615a66fd4502be2e029947b98e30f684bf48c861d9b7f10b00178070bdea33184e096601a1f2edb4e9094e757b238105ccec

test:
  secret_key_base: 65aeff3a2343e05f42a6b1fbf838c6fff4fee89138bffdff2c4f0abcc3953f1c0d3ef6f42f8d3339c4d14e38ba14def4eeac7c5d6af8772be1ee4aec64642630

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
